apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: my-app-container
        image: gcr.io/conductive-bank-401005/backend:blatest
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
         

---

apiVersion: v1
kind: Service
metadata:
  name: back-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
